apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: NodePort
  selector:
    type: backend
  ports:
  - port: 80           # port exposé par le service
    targetPort: 80     # port ciblé du pod 
    nodePort: 30180    # port exposé par tous les noeuds du cluster
