apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-<prenom>
spec:
  selector:
    matchLabels:
      tiers: backend-<prenom>
  template:
    metadata:
      labels:
        tiers: backend-<prenom>
    spec:
      containers:
      - name: webapp-container
        image: yannisbourree/exo-webapp-dotnet:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
          - name: BACKGROUND_COLOR
            value: "#03bef1"
          - name: DB_ADDRESS
            value: "mongo-<prenom>"
          - name: DB_PORT
            value: "27017"
          - name: DB_USERNAME
            value: "root"
          - name: DB_PASSWORD
            value: "example"
