apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-db-<prenom>
spec:
  selector:
    matchLabels:
      tiers: ###-<prenom>
  template:
    metadata:
      labels:
        tiers: ###-<prenom>
    spec:
      containers:
      - name: mongo-db
        image: mongo:5.0.3
        ports:
        - containerPort: 27017
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            value: "root"
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: "example"

