apiVersion: v1
kind: Service
metadata:
  name: mongo-<prenom>
spec:
  type: ###          # Besoin d'être accessible que dans le cluster  
  selector:
    tiers: ###-<prenom>        # Même label que les pods dont il gère le trafic
  ports:
  - port: 27017
    targetPort: 27017

