apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: formateur  
spec:
  type: NodePort
  selector:
    tiers: backend
  ports:
  - port: 80
    targetPort: 80
    nodePort: _PORT_BACKEND_