apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace:   
spec:
  type: NodePort
  selector:
    tiers: backend
  ports:
  - port: 80
    targetPort: 80
    nodePort: 3010_NUMBER_