apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: stu_NUMBER_  
spec:
  replicas: ###                 # A remplir
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate  
  selector:
    matchLabels:
      tiers: ###                # A remplir
  template:
    metadata:
      labels:
        tiers: ###              # A remplir
    spec:
      containers:
      - name: webapp-container
        image: fgtech/backend-todolist:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: ###    # A remplir
        env:
          - name: BACKGROUND_COLOR
            value: "#03bef1"
