apiVersion: apps/v1
kind: Deployment
metadata:       
 name: dep-demo 
 namespace: stu_NUMBER_
spec:           
 replicas: 3    
 selector:      
   matchLabels:
     env: bad  # good / bad
 template:      
   metadata:    
     labels:
       env: good
   spec:        
     containers:
     - name: nginx
       image: nginx:1.25.3-alpine
