apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: stu_NUMBER_  
spec:
  selector:
    matchLabels:
      tiers: frontend
  template:
    metadata:
      labels:
        tiers: frontend
    spec:
      containers:
      - name: frontend-container
        image: fgtech/frontend-todolist:stu_NUMBER_
        imagePullPolicy: Always
        ports:
        - containerPort: 81
        envFrom:
          - configMapRef:
              name: frontend-configmap             
      #Ajouter le nom du Node où le planifier
