apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: _PRENOM_
spec:
  replicas: 1
  selector:
    matchLabels:
      tiers: backend
  template:
    metadata:
      labels:
        tiers: backend
    spec:
      containers:
      - name: webapp-container
        image: fgtech/backend-todolist:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
          - name: BACKGROUND_COLOR
            value: "#03bef1"
        ### Définir les 3 Types de probes

