apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-ingress
  namespace: _PRENOM_  
  annotations:
  # https://kubernetes.github.io/ingress-nginx/examples/rewrite/#rewrite-target  
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  # ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: ###              # path backend
        pathType: Prefix
        backend:
          service:
            name: ###          # Service ciblé
            port:
              number: ###      # Port ciblé du service