apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
  namespace: <prenom>  
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox
            command:
            - /bin/sh
            - -c
            - date;
              echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure