apiVersion: v1
kind: Pod
metadata:
  name: mysql-client
  namespace: stu_NUMBER_
spec:
  containers:
  - name: mysql-container
    image: mysql:5.7
    command: ['sh','-c', "sleep 1800m"]
    imagePullPolicy: IfNotPresent