apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: <prenom>  
spec:
  selector:
    matchLabels:
      tiers: frontend
  template:
    metadata:
      labels:
        tiers: frontend
    spec:
      containers:
      - name: frontend-container
        image: fgtech/frontend-todolist:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 81
        envFrom:
          - configMapRef:
              name: frontend-configmap
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "150m"                

