apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: stu_NUMBER_  
spec:
  replicas: 1
  selector:
    matchLabels:
      tiers: frontend
  template:
    metadata:
      labels:
        tiers: frontend
    spec:
      containers:
      - name: frontend-container
        image: fgtech/frontend-todolist:stu_NUMBER_
        imagePullPolicy: Always
        ports:
        - containerPort: 81
        env:
        - name: BACK_URL
          value: "_PROTOCOLE_://_DOMAIN_NAME_/stu_NUMBER_-back"

