apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-configmap
data:
  BACKGROUND_COLOR: "#"
  DB_ADDRESS: ""
  DB_PORT: ""
  DB_USERNAME: ""   # le même que dans la configmap db
  DB_PASSWORD: ""   # le même que dans la configmap db
