apiVersion: apps/v1
kind: Deployment
metadata:
  name: angularapp
spec:
  selector:
    matchLabels:
      type: frontend
  template:
    metadata:
      labels:
        type: frontend
    spec:
      containers:
      - name: front-container
        image: yannisbourree/exo-front-angular:1.00
        imagePullPolicy: Always
        ports:
        - containerPort: 81
        - containerPort: 27017
        envFrom: # utiliser envFrom pour injecter les clé/valeur en tant que var d'env
          ###        

