apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: <prenom>  
spec:
  replicas: 1
  selector:
    matchLabels:
      tiers: backend
  template:
    metadata:
      labels:
        tiers: backend
        app: tutorial
    spec:
      containers:
      - name: webapp-container
        image: fgtech/backend-todolist:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        envFrom:
        - secretRef:
            name: backend-secret
        - configMapRef:
            name: backend-configmap         
      topologySpreadConstraints:
      - # Définir pour répartir automatiquement sur chaque Node