apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: _PRENOM_  
spec:
  selector:
    matchLabels:
      tiers: frontend
  template:
    metadata:
      labels:
        tiers: frontend
        app: tutorial        
    spec:
      containers:
      - name: frontend-container
        image: fgtech/frontend-todolist:_STUDENT_
        imagePullPolicy: Always
        ports:
        - containerPort: 81
        envFrom:
          - configMapRef:
              name: frontend-configmap              