apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: hpa-demo-deployment
 namespace: <prenom>
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: hpa-demo
 minReplicas: 1
 maxReplicas: 10
 targetCPUUtilizationPercentage: 50