apiVersion: apps/v1
kind: Deployment
metadata:
 name: hpa-demo
 namespace: <prenom>
spec:
 selector:
   matchLabels:
     run: hpa-demo
 replicas: 1
 template:
   metadata:
     labels:
       run: hpa-demo
   spec:
     containers:
     - name: hpa-demo
       image: k8s.gcr.io/hpa-example
       ports:
       - containerPort: 80
       resources:
         requests:
           memory: "64Mi"
           cpu: "200m"
         limits:
           memory: "128Mi"
           cpu: "500m"