apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: <prenom>  
spec:
  type: NodePort
  selector:
    tiers: backend
  ports:
  - port: ###                # port exposé par le service
    targetPort: ###          # port ciblé du pod
    nodePort: _PORT_BACKEND_ # port exposé par tous les noeuds du cluster