apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-db
  namespace: stu_NUMBER_  
spec:
  replicas: 1
  selector:
    matchLabels:
      tiers: ###        # A remplir
  template:
    metadata:
      labels:
        tiers: ###      # A remplir
    spec:
      containers:
      - name: mongo-db-container
        image: mongo:5.0.3
        ports:
        - containerPort: 27017
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            value: "root"
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: "example"

