apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: _PRENOM_  
spec:
  replicas: 7
  strategy:
    rollingUpdate:
      maxSurge: 4
      maxUnavailable: 4  
  selector:
    matchLabels:
      tiers: backend
      user: _PRENOM_
  template:
    metadata:
      labels:
        tiers: backend
        user: _PRENOM_
    spec:
      containers:
      - name: webapp-container
        image: fgtech/backend-todolist:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        envFrom:
        - secretRef:
            name: backend-secret
        - configMapRef:
            name: backend-configmap
