apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-db
  namespace: _PRENOM_  
spec:
  selector:
    matchLabels:
      tiers: db
      user: _PRENOM_
  template:
    metadata:
      labels:
        tiers: db
        user: _PRENOM_
    spec:
      containers:
      - name: mongo-db
        image: mongo:5.0.3
        ports:
        - containerPort: 27017
        envFrom:
          - secretRef:
              name: db-secret