apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-db
  namespace: stu_NUMBER_  
spec:
  selector:
    matchLabels:
      tiers: db
      user: stu_NUMBER_
  template:
    metadata:
      labels:
        tiers: db
        user: stu_NUMBER_
    spec:
      containers:
      - name: mongo-db
        image: mongo:7.0.4
        ports:
        - containerPort: 27017
        envFrom:
          - secretRef:
              name: db-secret