apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace:   
spec:
  replicas: 1
  selector:
    matchLabels:
      tiers: frontend
  template:
    metadata:
      labels:
        tiers: frontend
    spec:
      initContainers:
      - name: init-frontend
        image: busybox:1.28
        command: ['sh', '-c',
                  "until nslookup backend-service._PRENOM_.svc.cluster.local; 
                  do echo en attente de backend-service; sleep 2; done"]    
      containers:
      - name: frontend-container
        image: fgtech/frontend-todolist:_STUDENT_
        imagePullPolicy: Always
        ports:
        - containerPort: 81
        env:
        - name: BACK_URL
          value: "http://_IP_LB_INGR_CONTR_/_PRENOM_"

