apiVersion: apps/v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: stu_NUMBER_
  labels:
    app: nginx
spec:
  containers:
    - name: nginx
      image: nginx:1.25.3-alpine
      ports:
      - containerPort: 80
      volumeMounts:
          - name: nginx-index-file
            mountPath: ### indiquer où monter le fichier de la configmap
  volumes:
    - name: nginx-index-file
      configMap:
        name: ### A remplir