apiVersion: batch/v1
kind: Job
metadata:
  name: job-demo
  namespace: stu_NUMBER_
spec:
  template:
    spec:
      containers:
      - name: pi
        image: perl:5.36 # OK: perl:5.34 - Error: 5.36
        command: ["perl",  "-Mbignum=bpi",
                 "-wle", "print bpi(2000)"]
      restartPolicy: Never
  backoffLimit: 4 # par défaut 6
  activeDeadlineSeconds: 100
  ttlSecondsAfterFinished: 100    