apiVersion: v1
kind: Pod
metadata:
  name: myconfigmapfile
  namespace: _PRENOM_
spec:
  containers:
    - name: busybox
      image: k8s.gcr.io/busybox
      command: [ "/bin/sh","-c","sleep 3600" ]
      # Configurer l'injection de la configMap en tant que fichiers