apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-<prenom>
spec:
  selector:
    matchLabels:
      tiers: backend-<prenom>
  template:
    metadata:
      labels:
        tiers: backend-<prenom>
    spec:
      containers:
      - name: webapp-container
        image: yannisbourree/exo-webapp-dotnet:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        envFrom:
        - secretRef:
            name: ###
        - configMapRef:
            name: ###
