apiVersion: v1
kind: Service
metadata:
  name: frontend-service-<prenom>
spec:
  type: NodePort
  selector:
    tiers: frontend-<prenom>
  ports:
  - port: 81
    targetPort: 81
    nodePort: _PORT_FRONTEND_
