apiVersion: apps/v1
kind: Deployment
metadata:
  name: angularapp-<prenom>
spec:
  selector:
    matchLabels:
      tiers: frontend-<prenom>
  template:
    metadata:
      labels:
        tiers: frontend-<prenom>
    spec:
      containers:
      - name: frontend-container
        image: yannisbourree/exo-front-angular:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 81
        envFrom:
          - configMapRef:
              name: frontend-configmap-<prenom>