apiVersion: apps/v1
kind: Deployment
metadata:
  name: angularapp
spec:
  selector:
    matchLabels:
      type: frontend
  template:
    metadata:
      labels:
        type: frontend
    spec:
      containers:
      - name: frontend-container
        image: yannisbourree/exo-front-angular:1.00
        imagePullPolicy: Always
        ports:
        - containerPort: 81
        envFrom:
          - configMapRef:
              name: frontend-configmap