apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: <prenom>  
spec:
  replicas: 1
  selector:
    matchLabels:
      tiers: frontend
  template:
    metadata:
      labels:
        tiers: frontend
    spec:
      containers:
      - name: frontend-container
        image: fgtech/frontend-todolist:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 81
        env:
        - name: BACK_URL
          value: "http://_IP_NODE_:_PORT_FRONTEND_"

