apiVersion: v1
kind: Pod
metadata:
  name: mypod
  namespace: stu_NUMBER_
  labels:
    name: mypod
spec:
  containers:
      - name: webappcontainer
        image: ###               # A remplir
        imagePullPolicy: Always
        ports:
        - containerPort: ###     # A remplir
        env:
          - name: ###            # A remplir
            value: "###"
